#syntax=docker/dockerfile-upstream:1
# DO NOT EDIT THIS FILE : Make yours changes in /utils/Dockerfile.*.blueprint)
FROM ubuntu:22.10
LABEL authors="Essosolam Justin (Nehiyr) POTCHONA  <potchjust@gmail.com>"
SHELL ["/bin/bash", "-o", "pipefail", "-c"]

# Fixes some weird terminal issues such as broken clear / CTRL+L
#ENV TERM=linux

# Ensure apt doesn't ask questions when installing stuff
ENV DEBIAN_FRONTEND=noninteractive

ARG PHP_VERSION=8.1
ENV PHP_VERSION=${PHP_VERSION}

# |--------------------------------------------------------------------------
# | Main PHP extensions
# |--------------------------------------------------------------------------
# |
# | Installs the main PHP extensions
# |

# see this github issue (https://github.com/oerdnj/deb.sury.org/issues/56)
RUN  DEBIAN_FRONTEND=noninteractive apt-get update \
    && apt-get install -y software-properties-common
RUN DEBIAN_FRONTEND=noninteractive  LC_ALL=en_US.UTF-8 add-apt-repository ppa:ondrej/php

# install php


# Install php an other packages
RUN apt-get update \
# |--------------------------------------------------------------------------
# | User
# |--------------------------------------------------------------------------
# |
# | Define a default user with sudo rights.
# |

RUN useradd -ms /bin/bash docker && adduser docker sudo
# Users in the sudoers group can sudo as root without password.
RUN echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers
