#syntax=docker/dockerfile-upstream:1
# DO NOT EDIT THIS FILE : Make yours changes in /utils/Dockerfile.*.blueprint)
FROM ubuntu:20.04
LABEL authors="Essosolam Justin (Nehiyr) POTCHONA  <potchjust@gmail.com>"
SHELL ["/bin/bash", "-o", "pipefail", "-c"]

# Fixes some weird terminal issues such as broken clear / CTRL+L
#ENV TERM=linux

# Ensure apt doesn't ask questions when installing stuff
ENV DEBIAN_FRONTEND=noninteractive

ARG PHP_VERSION=8.1
ENV PHP_VERSION=${PHP_VERSION}

# |
# | Setup prerequistes for php
# |

# see this github issue (https://github.com/oerdnj/deb.sury.org/issues/56)
RUN  apt-get update \
    && apt-get install -y software-properties-common
RUN LC_ALL=en_US.UTF-8 add-apt-repository ppa:ondrej/php

# install php

# |
# | Install php and base packages
# | i'll install additional packages when needed
# |

# Install php and base packages
RUN  apt-get update \
     && apt-get install -y --no-install-recommends \
        git \
        nano \
        sudo \
        iproute2 \
        openssh-client \
        procps \
        unzip \
        ca-certificates \
        curl \
        php${PHP_VERSION}-fpm \
        php${PHP_VERSION}-curl \
        php${PHP_VERSION}-mbstring \
        php${PHP_VERSION}-opcache \
        php${PHP_VERSION}-readline \
        php${PHP_VERSION}-xml \
        php${PHP_VERSION}-zip \
     && apt-get clean \
     && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* /usr/share/doc/*


# |
# | addional php package to support
# | i'll install additional packages when needed
# |  mysql postgrsql redis



RUN useradd -ms /bin/bash docker && adduser docker sudo
# Users in the sudoers group can sudo as root without password.
RUN echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers
